/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 pumpkinCat.gltf 
Author: TanishaBerry (https://sketchfab.com/TanishaBerry)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/pumpkin-cat-82bf19f3981647c48f59d780779aed13
Title: Pumpkin Cat
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model(props) {
  const { nodes, materials } = useGLTF("/pumpkinCat.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.pumpkin_MAIN_0.geometry}
        material={materials.MAIN}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.top_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-10.688, 3.648, 1.212]}
        rotation={[-Math.PI / 2, -0.128, 0]}
        scale={100}
      />
      <mesh
        geometry={nodes.paw_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-40.664, 46.754, 37.366]}
        rotation={[1.568, 0.055, -0.022]}
        scale={[-5.319, 7.608, 5.319]}
      />
      <mesh
        geometry={nodes.Cube_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-26.029, 36.486, 4.636]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={26.672}
      />
      <mesh
        geometry={nodes.Icosphere_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-34.507, 57.018, 33.473]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-6.855, 6.855, 6.855]}
      />
      <mesh
        geometry={nodes.Icosphere001_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-12.791, 58.901, 32.25]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[-6.855, 6.855, 6.855]}
      />
      <mesh
        geometry={nodes.Circle_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-12.395, 60.557, 38.756]}
        rotation={[2.825, 0, 0]}
        scale={[-2.625, 2.625, 2.625]}
      />
      <mesh
        geometry={nodes.Circle001_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-34.237, 58.828, 39.937]}
        rotation={[2.886, 0, 0]}
        scale={[-2.625, 2.625, 2.625]}
      />
      <mesh
        geometry={nodes.Cube001_MAIN_0.geometry}
        material={materials.MAIN}
        position={[-15.488, 93.497, 20.81]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[15.779, 27.176, 15.779]}
      />
    </group>
  );
}

useGLTF.preload("/pumpkinCat.gltf");
